# This workflow will build and deploy the application
name: Deploy to GH Packages

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  NODE_VERSION: "14.x"
  SEMANTIC_RELEASE_VERSION: 18.0.0

on:
  push:
    branches:
      - rc
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tag version and deploy to GH Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: authenticate GH Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ env.GITHUB_TOKEN }}" >> .npmrc
      - name: install
        run: npm ci
      - name: build
        run: npm run build --production
      - name: prune
        run: npm prune --production
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: ${{ env.SEMANTIC_RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.GITHUB_TOKEN }}

  sync:
    needs: deploy
    name: Sync master into RC
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: "refs/heads/master"
          target_branch: "rc"
          commit_message_template: "ci: 🛰 Sync master into rc (via GH Actions) [skip ci]"
